name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print working dir
      run: echo "${GITHUB_WORKSPACE}"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
    - name: Build and push the Docker image
      uses: docker/build-push-action@v6
      with:
        tags: |
          dockingotter1337/podinfo:latest
          dockingotter1337/podinfo:${{ github.sha }}


    
