name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
    - name: Build and push the Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          dockingotter1337/podinfo:latest
          dockingotter1337/podinfo:${{ github.sha }}
          
  
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: ubuntu-latest
    
    steps:
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_ID}}

    - name: 'deploy with gke-deploy cli'
      uses: 'google-github-actions/deploy-gke@v0.0.1'
      with:
        image: 'https://hub.docker.com/repository/docker/dockingotter1337/podinfo'
        app_name: 'podinfo'
        region: 'europe-west2-a'
        cluster_name: 'zonal-cluster'
        project_id: ${{ secrets.GKE_PROJECT }}
        namespace: 'default'
        expose: '8000'
    
    - name: 'get-deployments'
      shell: bash
      run: |
        kubectl get deployment
    
